export const TITLE_SUGGESTIONS = [
  "CEO", "Co-Founder", "Founder", "Founding Engineer", "Founding Designer",
  "CTO", "CFO", "COO", "CMO", "CRO", "CPO", "CIO", "CISO", "CHRO", "CDO",
  "President", "Vice President", "Executive Vice President", "Senior Vice President",
  "Managing Director", "General Manager", "Country Manager", "Regional Director",
  "VP of Sales", "VP of Marketing", "VP of Engineering", "VP of Product", "VP of Operations",
  "VP of Finance", "VP of HR", "VP of Customer Success", "VP of Business Development",
  "VP of Growth", "VP of Revenue", "VP of Demand Generation",
  "Head of Sales", "Head of Marketing", "Head of Engineering", "Head of Product",
  "Head of Operations", "Head of People", "Head of Talent", "Head of Customer Success",
  "Head of Partnerships", "Head of Business Development", "Head of Growth",
  "Head of Demand Generation", "Head of RevOps", "Head of Data", "Head of Design",
  "Sales Director", "Marketing Director", "Engineering Director", "Product Director",
  "Operations Director", "Finance Director", "HR Director", "IT Director",
  "Director of Sales", "Director of Marketing", "Director of Engineering",
  "Director of Product", "Director of Operations", "Director of People",
  "Director of Customer Success", "Director of Demand Generation",
  "Director of Business Development", "Director of RevOps", "Director of Growth",
  "Sales Manager", "Marketing Manager", "Engineering Manager", "Product Manager",
  "Senior Product Manager", "Group Product Manager", "Principal Product Manager",
  "Project Manager", "Program Manager", "Operations Manager", "Office Manager",
  "Account Manager", "Strategic Account Manager", "Key Account Manager",
  "Customer Success Manager", "Partnerships Manager", "Business Development Manager",
  "Demand Generation Manager", "Growth Manager", "Content Manager", "Brand Manager",
  "Community Manager", "Social Media Manager", "SEO Manager", "PPC Manager",
  "Event Manager", "Field Marketing Manager", "Product Marketing Manager",
  "Lifecycle Marketing Manager", "Performance Marketing Manager",
  "Account Executive", "Senior Account Executive", "Enterprise Account Executive",
  "Mid-Market Account Executive", "SMB Account Executive", "Inside Sales Representative",
  "Outside Sales Representative", "Field Sales Representative",
  "Sales Development Representative", "Business Development Representative",
  "Sales Engineer", "Solutions Engineer", "Solutions Architect", "Solutions Consultant",
  "Pre-Sales Engineer", "Implementation Manager", "Onboarding Manager",
  "Customer Success Specialist", "Customer Experience Manager",
  "Software Engineer", "Senior Software Engineer", "Staff Software Engineer",
  "Principal Software Engineer", "Distinguished Engineer", "Software Architect",
  "Engineering Lead", "Tech Lead", "Frontend Engineer", "Backend Engineer",
  "Full Stack Engineer", "Mobile Engineer", "iOS Engineer", "Android Engineer",
  "DevOps Engineer", "Site Reliability Engineer", "Platform Engineer",
  "Infrastructure Engineer", "Cloud Engineer", "Security Engineer",
  "Data Engineer", "Machine Learning Engineer", "AI Engineer", "MLOps Engineer",
  "Data Scientist", "Senior Data Scientist", "Data Analyst", "Business Analyst",
  "Analytics Engineer", "BI Analyst", "Research Engineer",
  "Product Designer", "Senior Product Designer", "UX Designer", "UI Designer",
  "Visual Designer", "Brand Designer", "Design Lead", "Design Director",
  "Marketing Specialist", "Content Strategist", "Content Writer", "Copywriter",
  "Technical Writer", "Editor", "Public Relations Manager", "Communications Manager",
  "Recruiter", "Senior Recruiter", "Technical Recruiter", "Talent Acquisition Manager",
  "People Operations Manager", "HR Manager", "HR Business Partner",
  "Finance Manager", "Controller", "Treasurer", "Accountant", "Financial Analyst",
  "FP&A Manager", "FP&A Director", "Revenue Operations Manager",
  "Sales Operations Manager", "Marketing Operations Manager",
  "Investor", "Partner", "Principal", "Associate", "Venture Partner",
  "General Partner", "Managing Partner", "Operating Partner", "Angel Investor",
  "Consultant", "Senior Consultant", "Management Consultant", "Strategy Consultant",
  "Advisor", "Board Member", "Chairman", "Director",
  "Owner", "Proprietor", "Entrepreneur", "Independent Contractor", "Freelancer",
  "Lawyer", "General Counsel", "Legal Counsel", "Compliance Officer",
  "Procurement Manager", "Supply Chain Manager", "Logistics Manager",
  "Realtor", "Real Estate Agent", "Doctor", "Physician", "Surgeon", "Nurse",
  "Teacher", "Professor", "Researcher", "Scientist", "Engineer",
  "Architect", "Civil Engineer", "Mechanical Engineer", "Electrical Engineer",
];

export const INDUSTRY_SUGGESTIONS = [
  "Software Development", "SaaS", "Information Technology & Services",
  "Computer Software", "Internet", "Artificial Intelligence", "Machine Learning",
  "Cybersecurity", "Computer & Network Security", "Cloud Services",
  "Data Infrastructure & Analytics", "Big Data", "Developer Tools",
  "Computer Hardware", "Consumer Electronics", "Semiconductors",
  "Telecommunications", "Wireless", "Networking",
  "Financial Services", "Banking", "Investment Banking", "Investment Management",
  "Venture Capital & Private Equity", "Capital Markets", "Insurance",
  "FinTech", "InsurTech", "Cryptocurrency", "Blockchain",
  "Accounting", "Tax Services",
  "Marketing & Advertising", "Public Relations & Communications",
  "Market Research", "Media Production", "Broadcast Media", "Online Media",
  "Publishing", "Newspapers", "Writing & Editing", "Animation", "Graphic Design",
  "Design Services", "Architecture & Planning",
  "E-commerce", "Retail", "Wholesale", "Consumer Goods", "Apparel & Fashion",
  "Cosmetics", "Luxury Goods & Jewelry", "Sporting Goods",
  "Food & Beverages", "Restaurants", "Wine & Spirits", "Dairy", "Fishery",
  "Tobacco", "Consumer Services",
  "Healthcare", "Hospitals & Health Care", "Medical Devices", "Medical Practice",
  "Mental Health Care", "Pharmaceuticals", "Biotechnology", "Health, Wellness & Fitness",
  "Veterinary",
  "Education", "Higher Education", "Primary/Secondary Education", "E-Learning",
  "EdTech", "Professional Training & Coaching", "Research",
  "Real Estate", "Commercial Real Estate", "Construction", "Building Materials",
  "Architecture", "Civil Engineering",
  "Manufacturing", "Industrial Automation", "Mechanical or Industrial Engineering",
  "Electrical/Electronic Manufacturing", "Automotive", "Aerospace", "Defense",
  "Maritime", "Shipbuilding", "Renewables & Environment", "Oil & Energy",
  "Mining & Metals", "Plastics", "Chemicals", "Glass, Ceramics & Concrete",
  "Logistics & Supply Chain", "Transportation/Trucking/Railroad",
  "Warehousing", "Package/Freight Delivery", "Maritime & Shipping",
  "Airlines/Aviation", "Travel & Tourism", "Leisure, Travel & Tourism",
  "Hospitality", "Hotels & Hospitality", "Restaurants & Food Services",
  "Recreational Facilities & Services", "Sports", "Entertainment",
  "Music", "Motion Pictures & Film", "Gambling & Casinos", "Performing Arts",
  "Fine Art", "Museums & Institutions",
  "Legal Services", "Law Practice", "Alternative Dispute Resolution",
  "Government Administration", "International Affairs", "Public Policy",
  "Public Safety", "Law Enforcement", "Military", "Judiciary",
  "Nonprofit Organization Management", "Civic & Social Organization",
  "Religious Institutions", "Philanthropy", "Fundraising", "Think Tanks",
  "Human Resources", "Staffing & Recruiting", "Outsourcing/Offshoring",
  "Management Consulting", "Business Consulting", "Strategy Consulting",
  "Professional Services", "Executive Office", "Translation & Localization",
  "Information Services", "Library", "Archives",
  "Agriculture", "Farming", "Ranching", "Forestry", "Environmental Services",
  "Renewable Energy Power Generation",
  "Utilities", "Electrical Power", "Gas & Pipeline",
  "Furniture", "Paper & Forest Products", "Printing", "Packaging & Containers",
];

export const LOCATION_SUGGESTIONS = [
  "United States", "Canada", "United Kingdom", "Ireland", "Australia",
  "New Zealand", "Singapore", "India", "Germany", "France", "Spain", "Italy",
  "Netherlands", "Belgium", "Luxembourg", "Switzerland", "Austria", "Sweden",
  "Norway", "Denmark", "Finland", "Iceland", "Poland", "Czech Republic",
  "Slovakia", "Hungary", "Romania", "Bulgaria", "Greece", "Portugal",
  "Estonia", "Latvia", "Lithuania", "Croatia", "Slovenia", "Serbia",
  "Ukraine", "Russia", "Turkey", "Israel", "United Arab Emirates",
  "Saudi Arabia", "Qatar", "Kuwait", "Bahrain", "Oman", "Jordan", "Lebanon",
  "Egypt", "Morocco", "Tunisia", "South Africa", "Kenya", "Nigeria", "Ghana",
  "Ethiopia", "Tanzania", "Uganda", "Rwanda", "Algeria",
  "Japan", "South Korea", "China", "Hong Kong", "Taiwan", "Thailand",
  "Vietnam", "Indonesia", "Malaysia", "Philippines", "Pakistan", "Bangladesh",
  "Sri Lanka", "Nepal",
  "Mexico", "Brazil", "Argentina", "Chile", "Colombia", "Peru", "Uruguay",
  "Venezuela", "Ecuador", "Costa Rica", "Panama", "Dominican Republic",
  "Guatemala", "Honduras", "El Salvador",
  "Europe", "EMEA", "APAC", "LATAM", "North America", "MENA", "DACH",
  "Benelux", "Nordics", "Eastern Europe", "Western Europe", "Southeast Asia",
  "New York", "New York City", "San Francisco", "San Francisco Bay Area",
  "Los Angeles", "Greater Los Angeles", "Seattle", "Greater Seattle Area",
  "Austin", "Boston", "Greater Boston", "Chicago", "Denver", "Miami",
  "Atlanta", "Dallas", "Dallas-Fort Worth", "Houston", "Philadelphia",
  "Washington DC", "Washington DC-Baltimore Area", "Phoenix", "San Diego",
  "Portland", "Minneapolis", "Detroit", "Pittsburgh", "Nashville",
  "Charlotte", "Salt Lake City", "Raleigh", "Tampa", "Orlando",
  "Toronto", "Greater Toronto Area", "Vancouver", "Montreal", "Calgary", "Ottawa",
  "London", "Greater London", "Manchester", "Birmingham", "Edinburgh", "Bristol",
  "Dublin", "Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart",
  "Paris", "Lyon", "Marseille", "Toulouse",
  "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Brussels", "Antwerp",
  "Madrid", "Barcelona", "Valencia", "Lisbon", "Porto",
  "Milan", "Rome", "Turin", "Florence", "Naples",
  "Zurich", "Geneva", "Basel", "Vienna", "Salzburg",
  "Stockholm", "Gothenburg", "Copenhagen", "Oslo", "Helsinki",
  "Warsaw", "Krakow", "Prague", "Budapest", "Bucharest", "Athens",
  "Tel Aviv", "Jerusalem", "Dubai", "Abu Dhabi", "Riyadh", "Doha",
  "Bangalore", "Mumbai", "Delhi", "Gurgaon", "Hyderabad", "Chennai", "Pune",
  "Kolkata", "Ahmedabad", "Noida",
  "Tokyo", "Osaka", "Seoul", "Beijing", "Shanghai",
  "Shenzhen", "Guangzhou", "Taipei", "Bangkok", "Ho Chi Minh City", "Hanoi",
  "Jakarta", "Kuala Lumpur", "Manila", "Karachi", "Lahore", "Islamabad",
  "Dhaka",
  "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra",
  "Auckland", "Wellington",
  "Mexico City", "Monterrey", "Guadalajara",
  "Sao Paulo", "Rio de Janeiro", "Brasilia", "Buenos Aires", "Santiago",
  "Bogota", "Medellin", "Lima", "Quito", "Montevideo",
  "Cape Town", "Johannesburg", "Cairo", "Nairobi", "Lagos", "Accra",
  "Remote", "Worldwide",
];

export const KEYWORD_SUGGESTIONS = [
  "B2B", "B2C", "SaaS", "PLG", "Product-Led Growth", "Enterprise", "Mid-Market",
  "SMB", "Startup", "Scaleup", "Bootstrapped", "VC-Backed", "Series A",
  "Series B", "Series C", "Pre-Seed", "Seed", "Growth-Stage", "Late-Stage",
  "Sales", "Outbound", "Inbound", "Pipeline", "Quota", "Revenue", "ARR",
  "MRR", "ACV", "LTV", "CAC", "Payback Period", "Net Retention", "Gross Retention",
  "Churn", "Expansion", "Upsell", "Cross-Sell", "Renewals", "Activation",
  "Onboarding", "Adoption", "Engagement", "Retention", "Conversion",
  "Cold Outreach", "Cold Email", "Cold Calling", "Multichannel", "Omnichannel",
  "LinkedIn Outreach", "LinkedIn Automation", "Account-Based Marketing", "ABM",
  "Account-Based Selling", "Account Mapping", "Intent Data", "Buying Intent",
  "Signal-Based Selling", "Triggered Outreach", "Sales Sequences",
  "Sales Cadence", "Sales Enablement", "Sales Engagement",
  "Demand Generation", "Lead Generation", "Lead Scoring", "Lead Routing",
  "Lead Qualification", "MQL", "SQL", "PQL", "Opportunity Management",
  "Forecasting", "Pipeline Reviews", "Deal Desk", "RevOps",
  "Growth", "Growth Marketing", "Growth Hacking", "Performance Marketing",
  "Content Marketing", "Content Strategy", "SEO", "SEM", "PPC", "Display Ads",
  "Social Media Marketing", "Influencer Marketing", "Affiliate Marketing",
  "Email Marketing", "Lifecycle Marketing", "Marketing Automation",
  "Product Marketing", "Brand Marketing", "Field Marketing", "Partner Marketing",
  "Hiring", "Hiring SDRs", "Hiring AEs", "Hiring Engineers", "Hiring Growth",
  "Recruiting", "Talent Acquisition", "Building a Team", "Scaling Team",
  "Series A Raise", "Just Raised", "New Funding", "Recently Funded",
  "Product Launch", "New Product", "Expanding to US", "Opening Office",
  "International Expansion", "Going Global", "New Market", "Geo Expansion",
  "Migration", "Replacing", "Switching From", "Evaluating", "RFP",
  "Tool Consolidation", "Stack Consolidation", "Cost Optimization",
  "Compliance", "GDPR", "SOC 2", "HIPAA", "ISO 27001", "Security",
  "Privacy", "Data Governance",
  "AI", "GenAI", "LLM", "RAG", "Embeddings", "Vector Database",
  "Automation", "Workflow Automation", "No-Code", "Low-Code",
  "Integration", "API", "Webhook", "SDK", "Open Source", "Self-Hosted",
  "Cloud", "Multi-Cloud", "Hybrid Cloud", "On-Premise", "AWS", "GCP", "Azure",
  "DevOps", "DevEx", "Observability", "Monitoring", "Logging", "Tracing",
  "Reliability", "Performance", "Scalability", "Latency", "Uptime",
  "Customer Success", "CX", "NPS", "CSAT", "Voice of Customer",
  "Product Analytics", "User Research", "Behavioral Analytics", "Heatmaps",
  "A/B Testing", "Experimentation", "Conversion Optimization", "CRO",
];

export const SIGNAL_KEYWORD_SUGGESTIONS = [
  "hiring SDRs", "hiring AEs", "hiring engineers", "hiring growth", "hiring sales",
  "hiring marketing", "hiring product manager", "hiring designer", "hiring CTO",
  "hiring VP of Sales", "hiring head of growth",
  "we're hiring", "join our team", "open roles", "growing team",
  "outbound", "cold outreach", "cold email", "LinkedIn outreach",
  "sales sequences", "multichannel outreach", "sales engagement",
  "just raised", "Series A", "Series B", "Series C", "new funding",
  "recently funded", "announcement",
  "product launch", "launching", "new product", "going GA", "general availability",
  "expanding to", "opening office", "international expansion", "global launch",
  "looking for", "recommendations for", "tools for", "alternatives to",
  "switching from", "replacing", "evaluating", "comparing",
  "pipeline", "quota", "revenue", "growth", "scaling",
  "ABM", "intent data", "signal-based selling",
  "AI", "GenAI", "LLM", "RAG", "automation", "workflow",
  "compliance", "SOC 2", "HIPAA", "GDPR",
];
