/* Generated by scripts/build-icon-font.mjs — do not edit by hand. */
/* Hash query busts the immutable cache when the icon set changes. */
export const ICON_FONT_URL = "/fonts/material-symbols-outlined.woff2?v=1feb39dd";
